version: '3'

services:
  jekyll:
    image: jekyll/jekyll:latest
    container_name: online-cv
    command: jekyll serve --watch --force_polling --verbose
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll